apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: coupon
  labels:
    app: mysql-label
spec:
  replicas: 1
  serviceName: mysql-service
  selector:
    matchLabels:
      app: mysql-label
  template:
    metadata:
      labels:
        app: mysql-label
    spec:
      containers:
        - name: mysql-container
          image: mysql:8
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: TZ
              value: Asia/Seoul
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: MYSQL_DATABASE
              value: "couponDB"
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-volume-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: coupon
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS `couponDB` DEFAULT CHARACTER SET utf8;
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: coupon
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube