apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: coupon
  labels:
    app: mysql-label
spec:
  selector:
    app: mysql-label
  clusterIP: None
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306