apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: coupon
  labels:
    app: redis-label
spec:
  selector:
    app: redis-label
  clusterIP: None
  ports:
    - name: redis-port
      port: 6379
