apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  namespace: coupon
  labels:
    app: server-label
spec:
  selector:
    app: server-label
  type: LoadBalancer
  ports:
    - name: server-port
      protocol: TCP
      port: 80
      targetPort: 8000


